import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { generateBlogArticle, suggestBlogTopics } from "@/lib/ai/blog-generator";
import { slugify } from "@/lib/utils";

export async function GET(request: NextRequest) {
  // 1. Verify CRON_SECRET
  const authHeader = request.headers.get("authorization");
  const cronSecret = process.env.CRON_SECRET;
  if (cronSecret && authHeader !== `Bearer ${cronSecret}`) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  try {
    // 2. Check if we already generated an article this week
    const oneWeekAgo = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000);
    const recentAutoGenerated = await prisma.blogPost.count({
      where: {
        createdAt: { gte: oneWeekAgo },
        status: "DRAFT",
        // Use a tag to identify auto-generated articles
        tags: { has: "auto-generado" },
      },
    });

    if (recentAutoGenerated > 0) {
      return NextResponse.json({ message: "Already generated this week", skipped: true });
    }

    // 3. Get existing blog titles to avoid repetition
    const existingPosts = await prisma.blogPost.findMany({
      select: { title: true },
      orderBy: { createdAt: "desc" },
      take: 20,
    });
    const existingTitles = existingPosts.map(p => p.title);

    // 4. Get a topic suggestion
    const topics = await suggestBlogTopics(existingTitles);
    const topic = topics[0]; // Use the first suggestion

    if (!topic) {
      return NextResponse.json({ message: "No topic generated", skipped: true });
    }

    // 5. Generate the article
    // Pick a category based on the topic content (or default to GUIAS)
    const categoryKeywords: Record<string, string> = {
      cuidado: "CUIDADOS",
      limpiar: "CUIDADOS",
      mantener: "CUIDADOS",
      tendencia: "TENDENCIAS",
      moda: "TENDENCIAS",
      plata: "MATERIALES",
      oro: "MATERIALES",
      cobre: "MATERIALES",
      orfebre: "ORFEBRES",
      artesano: "ORFEBRES",
      chile: "CULTURA",
      tradición: "CULTURA",
      guía: "GUIAS",
      comprar: "GUIAS",
      regalo: "GUIAS",
    };

    let targetCategory: any = "GUIAS";
    const topicLower = topic.toLowerCase();
    for (const [keyword, category] of Object.entries(categoryKeywords)) {
      if (topicLower.includes(keyword)) {
        targetCategory = category;
        break;
      }
    }

    const article = await generateBlogArticle({
      topic,
      keywords: [topic.split(" ").slice(0, 3).join(" ")],
      targetCategory,
      includeProductLinks: true,
    });

    // 6. Find admin user to set as author (or first admin)
    const adminUser = await prisma.user.findFirst({
      where: { role: "ADMIN" },
      select: { id: true },
    });

    if (!adminUser) {
      return NextResponse.json({ error: "No admin user found" }, { status: 500 });
    }

    // 7. Create the blog post as DRAFT
    const slug = slugify(article.title) + "-" + Date.now().toString(36);

    const post = await prisma.blogPost.create({
      data: {
        slug,
        title: article.title,
        excerpt: article.excerpt,
        content: article.content,
        category: targetCategory,
        tags: [...article.tags, "auto-generado"],
        authorId: adminUser.id,
        status: "DRAFT",
        seoTitle: article.metaTitle,
        seoDescription: article.metaDescription,
        readingTime: Math.ceil(article.content.split(/\s+/).length / 200),
      },
    });

    return NextResponse.json({
      message: "Blog post generated",
      postId: post.id,
      title: post.title,
    });
  } catch (error) {
    console.error("[CRON] Blog auto-generate error:", error);
    return NextResponse.json(
      { error: "Failed to generate blog post" },
      { status: 500 },
    );
  }
}
